---
- name: Install and configure mongodb
  hosts: database
  become: true

  roles:
    - {role: community.mongodb.mongodb_linux, ntp_package: chrony, ntp_service: chronyd}
    - {role: community.mongodb.mongodb_repository, mongodb_version: "5.0"}
    - community.mongodb.mongodb_install
    - {role: community.mongodb.mongodb_mongod, bind_ip: "localhost,{{ ansible_default_ipv4.address }}", authorization: disabled, replicaset: false}
