---
- name: Fortune cookies
  hosts: targets

  tasks:
    - name: Install the fortune package
      ansible.builtin.apt:
        name: fortune
        state: present
        update_cache: true
      become: true

    - name: Run fortune
      ansible.builtin.command: fortune
      register: fortune_out

    - name: Display fortune results
      ansible.builtin.debug:
        var: fortune_out.stdout
